.setup-backend:
  variables:
    APP_DIRECTORY: backend
  extends: .setup

test-backend:
  extends: .setup-backend
  stage: test
  image: node:18
  script:
    - yarn
    - yarn test --ci --reporters=default --reporters=jest-junit --coverage
  artifacts:
    when: always
    paths:
    #   - backend/junit.xml
      - backend/coverage/
    reports:
      junit: backend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage/cobertura-coverage.xml

# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
build-backend:
  extends: .setup-backend
  stage: build
  image: '${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/cluster-integration/auto-build-image:${AUTO_BUILD_IMAGE_VERSION}'
  needs: [test-backend]
  variables:
    DOCKER_TLS_CERTDIR: ''
  services:
    - name: 'docker:20.10.12-dind'
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375']
  script:
    - |
      export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$APP_DIRECTORY}
      export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
    - /build/build.sh
    - |
      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
        echo "Pushing latest tag"
        docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_APPLICATION_REPOSITORY:latest
        docker image push $CI_APPLICATION_REPOSITORY:latest
      elif [[ -n "$CI_COMMIT_REF_SLUG" ]]; then
        echo "Pushing branch ref \"$CI_COMMIT_REF_SLUG\""
        docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_APPLICATION_REPOSITORY:$CI_COMMIT_REF_SLUG
        docker image push $CI_APPLICATION_REPOSITORY:$CI_COMMIT_REF_SLUG
      fi
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        echo "Pushing $CI_COMMIT_TAG tag"
        docker tag $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG $CI_APPLICATION_REPOSITORY:$CI_COMMIT_TAG
        docker image push $CI_APPLICATION_REPOSITORY:$CI_COMMIT_TAG
      fi
